### PR TITLE
Fix Proton installed EGS games not found

### LINKED ISSUE #165: Import Epic Games from original launcher on the Steam Deck
Hi there.

I am having huge trouble getting BoilR to recognize any of my Epic Games.
I installed the Epic Games Launcher using Proton and then imported it as a non Steam game.
I installed Assassins Creed Origins and it runs perfectly using the Epic launcher.
However, I would like to run it as the game per se under SteamOS using a BoilR shortcut.

After a lot of failures I even tried the following command lines in the config of BoilR...

[epic_games]
enabled = true
location = "/home/deck/.local/share/Steam/steamapps/compatdata/3091106007/pfx/drive_c/ProgramData/Epic/EpicGamesLauncher/Data/Manifests"
create_symlinks = true

And no matter how I change any of the location info I get nothing.
Any help would be greatly appreciated.
Thanks!

### PR DESCRIPTION
**Pull request by ProgDroid**
Fixes #165 

I came across this issue earlier today after setting up EGS on my Steam Deck, so I thought I'd give it a go.

Previously, `all_manifests` would be consumed by the for loop, so would then be collected into an empty Vec.

This PR changes how the manifests are filtered to be all in one go and moves the handling of Windows paths to where the manifest is parsed.

Tested on the Steam Deck with EGS installed using Proton, games are now found as expected. Also tested on Windows 11.

Appreciate any feedback!

### CODE REVIEW

File: src/platforms/egs/get_manifests.rs [hunk 1]
```diff
@@ -79,12 +57,40 @@ fn is_game_launchable(manifest: &ManifestItem) -> bool {
     (!manifest.launch_executable.is_empty()) || (manifest.is_managed)
 }
 
-fn get_manifest_item(dir_entry: DirEntry) -> Option<ManifestItem> {
+fn get_manifest_item(dir_entry: DirEntry, _path: Option<PathBuf>) -> Option<ManifestItem> {
```
Comment (PhilipK) [inline src/platforms/egs/get_manifests.rs:60]: Why is this named _path if it is actually used?
```suggestion
fn get_manifest_item(dir_entry: DirEntry, path: Option<PathBuf>) -> Option<ManifestItem> {
```

File: src/platforms/egs/get_manifests.rs [hunk 2]
```diff
@@ -79,12 +57,40 @@ fn is_game_launchable(manifest: &ManifestItem) -> bool {
...
     if let Some(extension) = dir_entry.path().extension() {
         if extension.eq("item") {
             if let Ok(file) = File::open(dir_entry.path()) {
                 let reader = BufReader::new(file);
-                return serde_json::from_reader(reader).ok();
+
+                #[cfg(target_family = "unix")]
+                {
+                    if let Ok(mut item) = serde_json::from_reader::<_, ManifestItem>(reader) {
+                        if let Some(compat_folder) = _path {
```
Comment (PhilipK) [inline src/platforms/egs/get_manifests.rs:69]:
```suggestion
                        if let Some(compat_folder) = path {
```

**Review by PhilipK — APPROVED** [review]
Great job finding this! Thank you so much.

I just have one suggestion, but it can be approved as is.

File: src/platforms/egs/get_manifests.rs (hunk 1 above)
Comment (ProgDroid) [reply src/platforms/egs/get_manifests.rs:60]: Removing the `_` causes a compiler warning on Windows and I wasn't sure if you'd have checks or workflows preventing builds with compiler warnings.
This just keeps the compiler happy on both platforms.

Comment (PhilipK) [reply src/platforms/egs/get_manifests.rs:60]: Alright, i can accept that.

**Comment by gnrw** [comment]
First of all, thank you very much for this great tool!

I tried the latest version 1.7.1 but still it fails to find the games installed by the Epic Game Launcher on Steam Deck.
The EGL was installed through Steam app adding the installation file as non steam games.
I ran the installation with GE-Proton7-37.
What more information do you need to fix the issue?

BoilR is working great with Heroic, Origin, Flatpack (interestingly only with linux executable version. The one gotten from Discover fails to find Flatpak apps..).
But it fails with Epic.
I hope this issue could be solved soon....

**Comment by PhilipK** [comment]
I think this is related to the sd card. Do you use one for epic games
